### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Dalewn** [FilenCloudDienste/filen-cli#213]
**Describe the bug**
I am running the docker container in s3 mode in a stack with backrest (restic).
The compose file looks like this:
```
version: "3.8"
services:
  filen-s3:
    container_name: filen-s3
    image: filen/cli:latest
    command: >
      --email ${FILEN_MAIL}
      --password ${FILEN_PASSWORD}
      s3
      --s3-access-key-id admin
      --s3-secret-access-key admin
    networks:
      - restic-network


  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    volumes:
      - ./backrest/data:/data
      - ./backrest/config:/config
      - ./backrest/cache:/cache
    environment:
      - BACKREST_DATA=/mnt/user/appdata/backrest/data # path for backrest data. restic binary and the database are placed here.
      - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
      - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
      - TZ=Berlin/Germany # set the timezone for the container, used as the timezone for cron jobs.
    restart: unless-stopped
    ports:
      - 9898:9898
    networks:
      - restic-network

networks:
  restic-network:
```
In backrest, the repo is configured like this:

```
{
  "id": "filen-s3",
  "uri": "s3:http://filen-s3:80/filen",
  "password": "test",
  "env": [
    "AWS_ACCESS_KEY_ID=admin",
    "AWS_DEFAULT_REGION=filen",
    "AWS_SECRET_ACCESS_KEY=admin"
  ],
  "flags": [
    "-o s3.list-objects-v1=true",
    "-o s3.bucket-lookup=path"
  ],
  "prunePolicy": {
    "maxUnusedPercent": 10,
    "schedule": {
      "clock": "CLOCK_LAST_RUN_TIME",
      "cron": "0 0 1 * *"
    }
  },
  "checkPolicy": {
    "readDataSubsetPercent": 0,
    "schedule": {
      "clock": "CLOCK_LAST_RUN_TIME",
      "cron": "0 0 1 * *"
    }
  },
  "commandPrefix": {}
}
```

Initializing the repo works as expected and the repo shows up in backrest.
It then tries to fetch the lists of snapshots and fails because the Last-Modified date in the header is malformed:

```
[unknown] failed to list snapshots: get snapshots for repo filen-s3: command "/bin/restic snapshots --json -o s3.list-objects-v1=true -o s3.bucket-lookup=path -o sftp.args=-oBatc..." failed: exit status 1
Output:
Fatal: unable to open config file: Stat: Last-Modified time format is invalid, failed with unable to parse  in any of the input formats: [Mon, 2 Jan 2006 15:04:05 GMT Mon, _2 Jan 2006 15:04:05 GMT Mon, _2 Jan 06 15:04:05 GMT]
Is there a repository at the following location?
s3:http://filen-s3:80/filen
```

Also creating a backup fails in a similar manner:
```
Failed to schedule backup: [unknown] failed to get snapshots for plan: get snapshots for plan "homepage2": command "/bin/restic snapshots --json -o s3.list-objects-v1=true -o s3.bucket-lookup=path -o sftp.args=-oBatc..." failed: exit status 1 Output: Fatal: unable to open config file: Stat: Last-Modified time format is invalid, failed with unable to parse in any of the input formats: [Mon, 2 Jan 2006 15:04:05 GMT Mon, _2 Jan 2006 15:04:05 GMT Mon, _2 Jan 06 15:04:05 GMT] Is there a repository at the following location? s3:http://filen-s3:80/filen 
```

**To Reproduce**
1. Start stack with above docker-compose.yaml
2. Access Backrest and configure source with above config (flags are optional and don't seem to make a difference)
3. See error
4. [Optional] Create a backup and see same error

**Expected behavior**
Last-Modified is returned in a way that restic can interpret.

**Logs/Screenshots**
See above
![Screenshot 2024-12-02 161917](https://github.com/user-attachments/assets/5d3094f8-7918-463b-9b6f-7648e96c84fb)

**System (please complete the following information):**
- Backrest version: version 1.6.2@2bd53596557724139fa25144ce8f0e8a715cb536
- **Filen CLI version:** v0.0.23
- which build of the CLI: filen/cli:latest (filen/cli:v0.0.23)
- OS: docker / docker-compose

**Additional context**
I am trying to run restic as backup solution using filen as the storage backend. I have tried using a mount instead of an s3 bucket, but that comes with significantly more config to get to work as a deployable container.
